### ISSUE TITLE
Issue, case c = 0

### ISSUE THREAD

**Issue by Okayzle** [dennis-classes/se2832-lab-01-isosceles-jsgar#6]
Issue: returned valid triangle in case c = 0, should return invalid

**Comment by Okayzle** [comment]
By the way, when you resolve it tell me and we can close it!

**Comment by jsgar** [comment]
Will do. I have a killer headache so I'll be working on this more later.

**Comment by Okayzle** [comment]
If you do it by Thursday afternoon I'm all good!

**Comment by jsgar** [comment]
Resolved: 0 1 1 exhibited correct behavior.
